### ISSUE TITLE
add new process step to determine whether a significant up or down trend exists over the time period

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/internal-analytics#152]
as part of adding trend markers:
![image](https://user-images.githubusercontent.com/2349007/27961116-502583b8-62f3-11e7-86db-5147d0b81149.png)

**Comment by aappling-usgs** [comment]
I'm finding "significant up or down trend" to be a more complicated idea than I first thought. @ldecicco-USGS , let's talk! First cut is a seasonal Kendall test, blocking on day of week, if there are at least four days of week with at least four observations. Otherwise (i.e., always for the 1-week window) using Mann-Kendall with no blocking. I wanted Kendall because the trends I see are almost always non-linear, and there's almost always a weekly pattern. I avoided blocking on actual seasons because we're only fitting to year (or less) of data at a time, and the apparent shape & scale of seasonality varies hugely by app. But I'm not at all confident in my approach yet, and would like to talk it through with you.

There are way more triangles for Year than for Month, and almost none for Week. I think that's reasonable, but if desired we could talk about approaches for Week that would be more likely to indicate a trend.

Next question, possibly for @jread-usgs - does tidy format work for turning these numbers into triangles for `visualize.portfolio_sessions_all`? In PR soon to come, I have columns for `viewID`, `scale` (`"Year"`/`"Month"`/`"Week"`), and `trend` (`"up"`/`"down"`/`"none"`).

**Comment by wdwatkins** [comment]
could do something simple with short term/long term moving averages too (long enough to smooth out the weekly signals)

**Comment by aappling-usgs** [comment]
that's a good idea for the 1-year and 1-month trends, thanks. if we decide to dig deeper into this, i'll include that as a possible competitor to the blocking approach.
